### PR TITLE
Add support for AWS EFS tagging

### PR DESCRIPTION
**Pull request by wadhwakabir**
* update for efs support

Co-authored-by: Kabir Wadhwa <kwadhwa@expediagroup.com>

### CODE REVIEW

**Comment by mtougeron** [comment]
Hey @wadhwakabir I ended up doing the refactoring to `k8s-pvc-tagger` this weekend. Not unexpectedly it's caused a goodly number of conflicts with your PR. I'd love it if you could rebase and resubmit the EFS code and I'll get it merged in. If that's too much of a hassle for you, I could always copy/paste the relevant code. The problem with that approach is that you'd lose the attribution for all your hard work. Let me know which approach you'd like to take. -Mike

**Comment by wadhwakabir** [comment]
> Hey @wadhwakabir I ended up doing the refactoring to `k8s-pvc-tagger` this weekend. Not unexpectedly it's caused a goodly number of conflicts with your PR. I'd love it if you could rebase and resubmit the EFS code and I'll get it merged in. If that's too much of a hassle for you, I could always copy/paste the relevant code. The problem with that approach is that you'd lose the attribution for all your hard work. Let me know which approach you'd like to take. -Mike

Sure, will raise a PR

**Comment by wadhwakabir** [comment]
@mtougeron fixed conflicts :)

**Review by mtougeron — CHANGES_REQUESTED** [review]
This looks great! Just a couple of minor tweaks.

I'll look into why the containerscan test is failing. It might be a configuration thing.
I'll also build a test image and test it live later today/tomorrow morning.

Thanks again for such an awesome contribution!

**Comment by mtougeron** [comment]
If you rebase to get https://github.com/mtougeron/k8s-pvc-tagger/pull/60 it'll fix the ContainerScan error. It was picking up a new CVE in the dependencies that I fixed just now.

**Comment by wadhwakabir** [comment]
all changes done, shall we merge ?

**Comment by mtougeron** [comment]
> all changes done, shall we merge ?

I didn't get a chance to test it this weekend. It's on my to-do list for today.

**Review by mtougeron — APPROVED** [review]

**Comment by mtougeron** [comment]
I'm working on sigstore/cosign this weekend. Once I get that working I'll drop a new release for you.

**Pull request merged**
